Move some common code used by models into birdfeeder
CoinAlpha/birdfeeder pull request #3
Opened 2022-02-28 20:22 UTC by sarinrp

2022-03-01 16:04 UTC, bitphage requested changes
- Need to transfer AWS tests as well

Also a side note, better to use more meaningful commit messages (not just "wip") - best to use atomic commits, one commit per new feature

2022-03-01 16:04 UTC, bitphage commented on birdfeeder/base.py
> +import os
Better rename to `birdfeeder/pydantic/base_settings.py`

2022-03-01 17:53 UTC, sarinrp commented
> * Need to transfer AWS tests as well
> 
> Also a side note, better to use more meaningful commit messages (not just "wip") - best to use atomic commits, one commit per new feature

Yes I plan to redo commits once everything is reviewed and okay to merge.

2022-03-02 17:30 UTC, bitphage approved these changes
LGTM

2022-03-02 17:30 UTC, merged